version: '3'

services:

  mysql:
    image: mysql:5.7
    volumes:
       - db-data:/var/lib/mysql
    restart: always  
    ports:
      - 3315:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
       - mysql
    image: wordpress:latest
    ports:
      - 9000:80
    restart: always
    volumes:
      - ./ccbr-theme:/var/www/html/wp-content/ccbr-theme
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
    links:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress        
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
    db-data:
