version: '3'

services:

  wpdb:
    image: mysql:5.7
    volumes:
       - db-data:/var/lib/mysql
    restart: always  
    ports:
      - 3315:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress

  wordpress:
    image: wordpress:4.8.3-php5.6-apache
    depends_on:
       - wpdb    
    ports:
      - 9000:80
    restart: always
    volumes:
      - ./ccbr-theme:/var/www/html/wp-content/themes/ccbr-theme
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
    links:
      - wpdb
    environment:
      WORDPRESS_DB_HOST: wpdb:3306       
      WORDPRESS_DB_PASSWORD: somewordpress

volumes:
    db-data:
